# Dockerfile.development
FROM php:7-apache
MAINTAINER Uwe Thiess <uwethiess@gmail.com>

# Setup Apache2 config
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# use your users $UID and $GID below
RUN groupadd apache-www-volume -g 503
RUN useradd apache-www-volume -u 503 -g 20

CMD ["apache2-foreground"]
